ice-lab/icestark

package.json, src/AppRoute.tsx, tests/index.spec.tsx
add Dom operation to fix hooks problem
=> feat: support hooks

package.json, src/AppRoute.tsx
remove useless history package
add run emptyAssets to empty dynamic assets before AppRoute unmount
=> Empty assets before unmount

README.md, README.zh-CN.md
=> chore: adjust readme

jest.setup.ts, package.json, packages/icestark-app/tests/index.spec.tsx, tests/index.spec.tsx
ref https://github.com/testing-library/dom-testing-library/issues/260
=> chore: migrate testing-library

package.json, src/AppRoute.tsx
=> fix: triggerPrevAppLeave when AppRoute unmount

packages/icestark-data/README.md, packages/icestark-data/package.json, packages/icestark-data/src/cache.ts, packages/icestark-data/src/event.ts, packages/icestark-data/src/index.ts, packages/icestark-data/src/store.ts, packages/icestark-data/src/utils.ts, packages/icestark-data/tests/cache.spec.tsx, packages/icestark-data/tests/event.spec.tsx, packages/icestark-data/tests/index.spec.tsx, packages/icestark-data/tests/store.spec.tsx, packages/icestark-data/tsconfig.json
=> feat: 增加 @ice/stark-data 解决通信问题

packages/icestark-app/package.json, packages/icestark-app/src/cache.ts, packages/icestark-app/src/getInIcestark.ts, packages/icestark-app/src/index.ts, packages/icestark-app/src/isInIcestark.ts, packages/icestark-app/tests/index.spec.tsx
=> feat: add getInIcestark api

src/AppRoute.tsx
chore: adjust child 2 sub-application in comment
=> chore: adjust comment

package.json, src/AppRoute.tsx, src/AppRouter.tsx, src/util/appLifeCycle.ts, src/util/capturedListeners.ts
fix: 修复 hash 路由下，AppLink 跳转失效的问题
fix: 修复 appLeave 不触发的问题
=> feat: fix hashType link

.eslintrc.js, src/AppRoute.tsx, src/AppRouter.tsx, src/util/appLifeCycle.ts, src/util/handleAssets.ts, tests/handleAssets.spec.tsx
#63 
子应用需实时获取 mountNode：
```js
if (isInIcestark()) {
registerAppEnter(() => {
ReactDOM.render(router(), getMountNode());
});
// make sure the unmount event is triggered
registerAppLeave(() => {
ReactDOM.unmountComponentAtNode(getMountNode());
});
} else {
ReactDOM.render(router(), document.getElementById('ice-container'));
}
```
=> feat: support cache url of sub application

.eslintrc.js, package.json, packages/icestark-app/tests/index.spec.tsx, src/AppRoute.tsx, src/AppRouter.tsx, src/util/appLifeCycle.ts, src/util/handleAssets.ts, src/util/renderComponent.tsx, tests/appLifeCycle.spec.tsx, tests/capturedListeners.spec.tsx, tests/handleAssets.spec.tsx, tests/index.spec.tsx
feat: 适配 icestark 和约定式路由共存方案 #53 
fix: 彻底修复 onAppEnter / onAppLeave 可能不触发的问题，优化 registerAppLeave 触发时机
feat: AppRoute component/render 渲染时也会触发 onAppEnter / onAppLeave
feat: component / render 改为 AppRoute 层触发渲染
feat: renderComponent 抽成公共方法
feat: 提高 history/eventListener 事件劫持时机
chore: 完善测试用例
=> release 1.4.0

package.json, src/AppRoute.tsx, tests/index.spec.tsx
=> fix: re-render if componentProps is changed

src/AppRoute.tsx, src/util/handleAssets.ts, tests/handleAssets.spec.tsx
=> fix: load entry source in root

src/AppRouter.tsx
React 16 之后 componentWillUnmout 是异步的 https://github.com/facebook/react/issues/11106
导致如果多次触发渲染的场景下上一次的内容在 didmout 前还没被清理
=> fix: hijack when component did mount

src/util/handleAssets.ts, tests/handleAssets.spec.tsx
fix: https://github.com/ice-lab/icestark/issues/99
=> fix: script regex

src/AppRoute.tsx
=> feat: optimize log

src/AppRoute.tsx, src/AppRouter.tsx, src/util/matchPath.ts, tests/matchPath.spec.tsx
=> feat: enhance config path

package.json, packages/icestark-module/package.json, packages/icestark-module/src/loader.ts, packages/icestark-module/src/modules.tsx, packages/icestark-module/tests/index.spec.tsx, packages/icestark-module/tests/loader.spec.ts, packages/icestark-sandbox/package.json, packages/icestark-sandbox/src/index.ts
=> feat: support load multi assets of stark-module

.github/workflows/ci.yml, package.json, packages/icestark-module/package.json, packages/icestark-module/src/loader.ts, packages/icestark-module/src/modules.tsx, packages/icestark-sandbox/package.json, packages/icestark-sandbox/src/index.ts, packages/icestark-sandbox/tests/index.spec.ts, setupJest.ts
=> fix: get unmount lifecycle

package.json, src/AppRouter.tsx
实例化 popStateEvent 时，仅需要传入 state 信息
Close https://github.com/ice-lab/icestark/issues/142
=> fix: error state of popStateEvent

src/util/appLifeCycle.ts, src/util/assist.ts, src/util/getMountNode.ts, src/util/global.ts, src/util/handleAssets.ts, src/util/umdLoader.ts
=> feat: 🎸 support umd js bundle

src/AppRoute.tsx, src/AppRouter.tsx, src/apps.ts, src/start.ts, src/util/handleAssets.ts, tests/index.spec.tsx
使用 AppRouter 时，由 React 生命周期控制相关 createMicroApp 的逻辑
=> fix: error redirection when use AppRouter

packages/icestark-app/tsconfig.json, packages/icestark-data/tsconfig.json, packages/icestark-module/tsconfig.json, packages/icestark-sandbox/tsconfig.json, tsconfig.json
Close https://github.com/alibaba/ice/issues/3711
sourceMap 由项目决定是否生成，组件构建默认不再生成
=> chore: remove sourceMap

package.json, src/AppRoute.tsx, src/AppRouter.tsx, tests/index.spec.tsx
=> fix: 🐛 fix onAppEnter and onAppLeave when using AppRouter

src/util/handleAssets.ts, tests/handleAssets.spec.tsx
=> feat: 🎸 new html parser

src/AppRoute.tsx, src/apps.ts
=> fix: 🐛 update container on every update

src/AppRouter.tsx, src/apps.ts, src/start.ts, src/util/handleAssets.ts, tests/handleAssets.spec.tsx
=> feat: 🎸 fetcher

src/AppRoute.tsx, src/AppRouter.tsx, src/apps.ts
=> fix: 🐛 start should invoked before create

packages/icestark-module/package.json, packages/icestark-module/src/MicroModule.tsx, packages/icestark-module/src/index.ts, packages/icestark-module/src/loader.ts, packages/icestark-module/src/modules.tsx, packages/icestark-module/src/runtime.helper.ts, packages/icestark-module/src/runtimeHelper.ts, packages/icestark-module/src/utils.ts, packages/icestark-sandbox/package.json, packages/icestark-sandbox/src/index.ts
=> @ice/stark-module 1.3.0

packages/icestark-sandbox/CHANGELOG.md, packages/icestark-sandbox/package.json, packages/icestark-sandbox/src/index.ts
=> feat: 🎸 support getAddedProperties & injection

packages/icestark-app/CHANGELOG.md, packages/icestark-app/package.json, packages/icestark-app/src/index.ts, packages/icestark-app/src/setBasename.ts, packages/icestark-app/tests/index.spec.tsx, packages/icestark-module/package.json
=> feat: 🎸 add setBasename function

CHANGELOG.md, package.json, src/apps.ts
=> fix: 🐛 retrieve assets

src/util/handleAssets.ts
=> fix: 🐛 absolute path may redirect incorrect address

CHANGELOG.md, package.json, packages/icestark-module/CHANGELOG.md, packages/icestark-module/README.md, packages/icestark-module/package.json, packages/icestark-module/src/modules.tsx, packages/icestark-module/src/runtimeHelper.ts, src/AppRouter.tsx, src/util/matchPath.ts, tests/index.spec.tsx
=> Release icestark 2.2.2

packages/icestark-module/src/MicroModule.tsx, packages/icestark-module/src/modules.tsx, packages/icestark-module/tests/index.spec.tsx, packages/icestark-sandbox/src/index.ts, packages/icestark-sandbox/tests/index.spec.ts
**What kind of change does this PR introduce?** (check at least one)
**Does this PR introduce a breaking change?** (check one)
=> refactor: modify letter spell

packages/icestark-module/README.md, packages/icestark-module/src/MicroModule.tsx, packages/icestark-module/src/index.ts, packages/icestark-module/src/loader.ts, packages/icestark-module/src/modules.tsx, packages/icestark-module/tests/index.spec.tsx
支持本地微模块加载，详见[RFC](https://github.com/ice-lab/icestark/issues/205)
=> feat: support local component

packages/icestark-sandbox/CHANGELOG.md, packages/icestark-sandbox/package.json, packages/icestark-sandbox/src/index.ts, packages/icestark-sandbox/tests/index.spec.ts
=> fix: 🐛 falsy values will trapped by proxy window

CHANGELOG.md, packages/icestark-app/CHANGELOG.md, packages/icestark-app/package.json, packages/icestark-app/src/setLibraryName.ts, src/util/getLifecycle.ts, tests/getLifecycle.spec.tsx
=> feat: 🎸 parse library the right way if library is an array

CHANGELOG.md, package.json, packages/icestark-app/CHANGELOG.md, packages/icestark-app/package.json, packages/icestark-app/src/setLibraryName.ts, packages/icestark-sandbox/CHANGELOG.md, packages/icestark-sandbox/package.json, packages/icestark-sandbox/src/index.ts, packages/icestark-sandbox/tests/index.spec.ts, src/util/getLifecycle.ts, tests/getLifecycle.spec.tsx
=> release 2.3.1

README.md, packages/icestark-app/README.md, packages/icestark-data/README.md, packages/icestark-sandbox/README.md
=> docs: modify chinese website link

packages/icestark-sandbox/src/index.ts, packages/icestark-sandbox/tests/index.spec.ts
✅ Closes: https://github.com/alibaba/ice/issues/4294
=> fix: 🐛 eval should not be bind

packages/icestark-sandbox/CHANGELOG.md, packages/icestark-sandbox/package.json, packages/icestark-sandbox/src/index.ts, packages/icestark-sandbox/tests/index.spec.ts
=> fix: 🐛 eventlistener should be store in this.eventListeners

packages/icestark-sandbox/src/index.ts, packages/icestark-sandbox/tests/index.spec.ts
=> refactor: 💡 temporary separate to sandbox

src/apps.ts
=> fix: 🐛 unexpectable sandbox's cleaning up when load module

tests/handleAssets.spec.tsx
=> test: 💍 fix slient pass

packages/icestark-data/CHANGELOG.md, packages/icestark-data/package.json, packages/icestark-data/src/event.ts, packages/icestark-data/src/store.ts, packages/icestark-data/tests/event.spec.tsx, packages/icestark-data/tests/store.spec.tsx
=> feat: 🎸 support symbol key for index

packages/icestark-sandbox/src/index.ts
=> chore: 🤖 sandbox setInterval spell error

website/docusaurus.config.js, website/package.json, website/yarn.lock
+ Add Google Analysis Tracking Id
=> feat: 🎸 add google analysis

website/docusaurus.config.js, website/package.json, website/yarn.lock
=> docs: ✏️ add algolia

src/AppRoute.tsx, src/AppRouter.tsx
=> fix: 🐛 activePath is ignored

src/util/handleAssets.ts, tests/handleAssets.spec.tsx
=> feat: 🎸 release type restrict for es module

.github/workflows/ci.yml, package.json, src/AppRoute.tsx, src/apps.ts, src/util/helpers.ts, src/util/loader.ts, src/util/loaders.ts, tests/loader.bundle.spec.ts, tests/loader.umd.setLibrary.spec.ts, tests/loader.umd.spec.ts, tsconfig.json
=> feat: es module

src/AppRouter.tsx, tests/index.spec.tsx
=> fix: 🐛 hashRouter changes twice

website/docs/api/ice-stark.md, website/docs/faq.md
=> docs: 🎸 add fqa + modify apis

packages/icestark-module/src/MicroModule.tsx, packages/icestark-module/src/modules.tsx
=> fix: 🐛 bypass unmount when loading

src/apps.ts, src/util/handleAssets.ts, src/util/helpers.ts, tests/handleAssets.spec.tsx
=> feat: 🎸 import asset cache

package.json
=> feat: 🎸 add module input

CHANGELOG.md, package.json, src/util/loaders.ts
=> fix: 🐛 wrap import

src/util/loaders.ts, src/util/prefetch.ts
=> fix: 🐛 narrow import error

packages/icestark-app/src/AppLink.tsx
=> fix: 🐛 empty search

CHANGELOG.md, package.json, packages/icestark-app/CHANGELOG.md, packages/icestark-app/package.json, packages/icestark-app/src/AppLink.tsx, packages/icestark-app/src/appHistory.ts, packages/icestark-app/src/index.ts, packages/icestark-app/src/registerAppEnter.ts, packages/icestark-app/src/registerAppLeave.ts, packages/icestark-app/src/util/normalizeArgs.ts, packages/icestark-app/tests/index.spec.tsx, packages/icestark-data/package.json, src/AppRouter.tsx, src/apps.ts, src/start.ts, src/util/globalConfiguration.ts, src/util/handleAssets.ts, src/util/loaders.ts, tests/AppRouter.spec.tsx, tests/handleAssets.spec.tsx, website/blog/03-icestark-2-7-0.md, website/docs/api/ice-stark-app.md, website/docs/guide/use-child/others.md
=> Release: 2.7.0

packages/icestark-module/src/modules.tsx, website/yarn.lock
在微模块umd包除了mount、unmount和default外，还有其他方法。所以需要获取已经加载的模块信息及loadModule信息。
=> 增加获取importModules方法及loadModule后的moduleInfo

packages/icestark/src/apps.ts
=> fix: 🐛 remove useless try-catch

packages/icestark-module/src/modules.tsx
Relates to https://github.com/ice-lab/icestark/pull/505
=> fix: 🐛 fast re-render will cause css flashing

packages/icestark-module/src/modules.tsx
=> bugfix: css clear bug when unmount earlier than exe module js

CHANGELOG.md, package.json, packages/icestark/src/apps.ts
=> fix: 🐛 append missing styles

CHANGELOG.md, packages/icestark/__tests__/AppRouter.spec.tsx, packages/icestark/__tests__/checkActive.spec.tsx, packages/icestark/__tests__/index.spec.tsx, packages/icestark/package.json, packages/icestark/src/AppRouter.tsx, packages/icestark/src/apps.ts, packages/icestark/src/util/checkActive.ts, packages/icestark/src/util/error.ts, website/src/codes/2.jsx, website/src/codes/3.jsx, website/src/codes/4.jsx, website/src/codes/5.jsx, website/src/codes/6.jsx, website/src/codes/7.jsx
=> fix: 🐛 empty value or undefined in activePath array should be ignored

CHANGELOG.md, package.json, packages/icestark/__tests__/AppRouter.spec.tsx, packages/icestark/__tests__/checkActive.spec.tsx, packages/icestark/__tests__/index.spec.tsx, packages/icestark/package.json, packages/icestark/src/AppRouter.tsx, packages/icestark/src/apps.ts, packages/icestark/src/util/checkActive.ts, packages/icestark/src/util/error.ts, packages/sandbox/CHANGELOG.md, packages/sandbox/__tests__/index.spec.ts, packages/sandbox/package.json, packages/sandbox/src/index.ts, pnpm-lock.yaml, website/docs/guide/use-child/others.md, website/docs/guide/use-child/vue.md, website/src/codes/2.jsx, website/src/codes/3.jsx, website/src/codes/4.jsx, website/src/codes/5.jsx, website/src/codes/6.jsx, website/src/codes/7.jsx
=> Release: 2.7.3

packages/sandbox/CHANGELOG.md, packages/sandbox/__tests__/index.spec.ts, packages/sandbox/package.json, packages/sandbox/src/index.ts
This reverts commit a44977a286864ca50ce09ffd908406c0f75b71ba. closes https://github.com/ice-lab/icestark/issues/192
=> Revert "Feat/sandbox inject custom proxy (#577)"

website/blog/00-icestark-2-4-0.md, website/blog/01-icestark-2-5-0.md, website/blog/02-icestark-2-6-0.md, website/blog/03-icestark-2-7-0.md, website/docs/api/ice-stark.md, website/docs/api/stark-module.md, website/docs/faq.md, website/docs/guide/advanced/communication.md, website/docs/guide/advanced/performance.md, website/docs/guide/concept/child.md, website/docs/guide/concept/workflow.md, website/docs/guide/micro-module.md, website/docs/guide/use-child/others.md, website/docs/guide/use-layout/react.md, website/docs/guide/use-layout/vue.md
=> docs: update

.github/workflows/ci.yml, .github/workflows/website.yml, CHANGELOG.md, packages/icestark/__tests__/handleAssets.spec.tsx, packages/icestark/package.json, packages/icestark/src/AppRoute.tsx, packages/icestark/src/AppRouter.tsx, pnpm-lock.yaml
Get location from props when location change controlled by react state such as ice.js 3.x.
=> feat: support custom AppRoute location by props

packages/icestark/src/AppRouter.tsx
fix AppRouter props type error. #667
=> fix(icestark): fix AppRouter props type #667

.github/workflows/ci.yml, CHANGELOG.md, package.json, packages/icestark-app/package.json, packages/icestark-app/src/AppLink.tsx, packages/icestark-module/__tests__/index.spec.tsx, packages/icestark-module/package.json, packages/icestark-module/src/MicroModule.tsx, packages/icestark/__tests__/global-umd-sample.js, packages/icestark/__tests__/loader.bundle.spec.ts, packages/icestark/__tests__/loader.runtime.spec.ts, packages/icestark/package.json, packages/icestark/src/AppRoute.tsx, packages/icestark/src/apps.ts, packages/icestark/src/util/handleAssets.ts, packages/icestark/src/util/loaders.ts, pnpm-lock.yaml
This pull request includes various updates and improvements to the `icestark` project, including new features, dependency updates, and code refactoring. The most important changes include adding support for the `runtime` option, updating dependencies, and refactoring the code for better type handling and error management.
=> Feat: support option runtime for UMD resource

CHANGELOG.md, packages/icestark/package.json, packages/icestark/src/util/handleAssets.ts
Fixing cache key handling for JavaScript resources.
=> fix:  unique cache key support in JavaScript resources

CHANGELOG.md, packages/icestark/package.json, packages/icestark/src/AppRoute.tsx, packages/icestark/src/apps.ts, packages/icestark/src/util/handleAssets.ts
This pull request updates the `@ice/stark` package to version 2.8.3 and introduces a new feature to support `runtime.url` as an array, enabling the loading of multiple types of resources. It also includes updates to the `apps.ts` file to handle this new functionality.
=> feat: support runtime.url to load multi type resource
